# Numpy의 배열 객체

In [1]:
# Numpy 패키지 불러오기
import numpy as np # 넘파이 패키지를 np라는 별칭으로 호출

#### [ ndarray 생성 ]

- ndarray(다차원 배열)객체는 아래의 주요 함수들을 통해 쉽게 생성이 가능하다. <br> 아래의 함수는 Numpy Package 내 디렉토리 구조로 되어 있으므로 **numpy.함수명** 과 같은 방법으로 사용 가능하다.

|메소드|기능|
|:------|:---------|
|array(object)|객체(object)를 배열로 반환함|
|arange([start,] stop, [step,])| start 숫자에서 step 간격으로 증가하여 end(end를 포함하지 않는)숫자까지 실수열을 생성 |
|ones(shape)| shape는 정수 또는 튜플 형태로 입력되어, shape 값에 따른 모든 값이 1인 배열을 생성 |
|zeros(shape)| shape는 정수 또는 튜플 형태로 입력되어, shape 값에 따른 모든 값이 0인 배열을 생성 |
|full(shape, fill_value)| shape는 정수 또는 튜플 형태로 입력되어, shape 값에 따른 모든 값이 fill_value인 배열을 생성 |
|identity(n)| 주 대각성분이 1인 행과 열의 수가 n개인 정사각 2차원 배열(항등행렬과 유사) |

## 1. N 차원 배열 생성하기

### 1차원 배열 생성하기

In [2]:
# 1d-array 생성
# array(object) : 객체(object)를 배열로 반환함 
np.array([1, 3, 5, 7, 9]) # 리스트객체를 1차원 배열로

array([1, 3, 5, 7, 9])

In [3]:
np.array('data') # 문자열객체를 1차원 배열로

array('data', dtype='<U4')

In [4]:
# arange([start, ]stop, [step, ])
# start 숫자에서 step 간격으로 증가해 end 전(end를 포함하지 않는) 숫자까지 숫자열 생성
np.arange(7) # 0에서 6까지 정수열 1차원 배열 생성

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
# arange는 정수형만 가능한 range()와는 달리 실수도 가능
np.arange(1, 6, 0.5) # 1에서 5까지 0.5씩 증가하는 실수열 1차원 배열 생성

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [6]:
# (참고) range()는 step에 실수가 되지 않아 오류
range(1, 6, 0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
# ones(shape)
# shape 값에 따른 모든 값이 1.(실수)인 배열을 생성
np.ones(5)  # 모든 값이 1.이고 요소가 5개인 1차원 배열 생성

array([1., 1., 1., 1., 1.])

In [8]:
# zeros(shape)
# shape 값에 따른 모든 값이 0.(실수)인 배열을 생성
np.zeros(5) # 모든 값이 0.이고 요소가 5개인 1차원 배열 생성

array([0., 0., 0., 0., 0.])

In [9]:
# full(shape, fill_value)
# shape 값에 따른 모든 값이 fill_value인 배열을 생성
np.full(5, 4.) # 모든 값이 4.(실수)이고 요소가 5개인 1차원 배열 생성

array([4., 4., 4., 4., 4.])

In [10]:
# 배열 객체의 데이터 타입(dtype)
# 4가 정수이므로 배열은 정수형이 됨
np.full(5, 4).dtype

dtype('int64')

In [11]:
# 4.은 실수이므로 배열은 실수형이 됨
np.full(5, 4.).dtype 

dtype('float64')

In [12]:
# 4가 정수이지만, dtype인자를 통해 float로 지정하면 실수형이 됨
np.full(5, 4, dtype = 'float').dtype

dtype('float64')

### 2차원 배열 생성하기

In [13]:
# 2d-array 생성
# 리스트 객체를 2차원 배열로
np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]) # 2행 5열

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [14]:
# 리스트 객체를 2차원 배열로
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # 3행 3열

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# 모든 값이 1(정수)이고 행의 수가 2, 열의 수가 5개인 2차원 배열 생성
np.ones((2,5), dtype = 'int') # dtype 생략할 경우 실수로 자동 생성

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
# 모든 값이 0(정수)이고 행의 수가 2, 열의 수가 5개인 2차원 배열 생성
np.zeros((2,5), dtype = 'int') # dtype 생략할 경우 실수로 자동 생성

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
# 모든 값이 5(정수)이고 행의 수가 2, 열의 수가 5개인 2차원 배열 생성
np.full((2,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [18]:
# 주 대각성분이 1인 행과 열의 수가 5개인 정사각 2차원 배열 생성(항등행렬과 유사)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 3차원 배열 생성하기

In [19]:
# 3d-array 생성
# 리스트 객체를 3차원 배열로
np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]], # 0층
    [[2, 4, 6, 8], [10, 12, 14, 16]], # 1층
    [[1, 3, 5, 7], [9, 11, 13, 15]] # 2층
         ]) # 3층 2행 4열

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16]],

       [[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]]])

In [20]:
# 모든 값이 1이고 3층 2행 4열인 3차원 배열 생성
np.ones((3, 2, 4), dtype = 'int') # dtype 생략할 경우 실수로 자동 생성

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [21]:
# 모든 값이 0이고 3층 2행 4열인 3차원 배열 생성
np.zeros((3, 2, 4), dtype = 'int') # dtype 생략할 경우 실수로 자동 생성

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [22]:
# 모든 값이 5이고 3층 2행 4열인 3차원 배열 생성
np.full((3, 2, 4), 5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]]])

## 2. N 차원 배열 확인하기

In [23]:
# ndarray 생성
# 1d-array
arr_1d = np.array([1, 2, 3, 4])

# 2d-array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # 2행 4열

# 3d-array
arr_3d = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]], # 0층
    [[2, 4, 6, 8], [10, 12, 14, 16]], # 1층
    [[1, 3, 5, 7], [9, 11, 13, 15]] # 2층
    ]) # 3층 2행 4열

In [24]:
# .shape
# 배열객체의 [층,] 행, [열]의 수
print(arr_1d.shape) # 1d-array의 경우 길이정보가 (길이, )와 같은 형태로 반환됨
print(arr_2d.shape)
print(arr_3d.shape) 

(4,)
(2, 4)
(3, 2, 4)


In [25]:
# .size
# 배열객체의 총 원소의 수
print(arr_1d.size)
print(arr_2d.size)
print(arr_3d.size)

4
8
24


In [26]:
# .ndim
# 배열객체의 차원의 수
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3
