# Numpy의 연산

In [1]:
# Numpy 패키지 불러오기
import numpy as np # 넘파이 패키지를 np라는 별칭으로 호출

## 1. N 차원 배열의 인덱싱과 슬라이싱

### 인덱싱

In [2]:
# 인덱싱
# 1d-array객체 생성
arr_1d = np.array([1, 2, 3, 4, 5])

In [3]:
print(arr_1d[0]) # 가장 처음(0번)으로부터 값 하나 참조
print(arr_1d[2]) # 2번 인덱스 위치로부터 값 하나 참조
print(arr_1d[4]) # 가장 마지막(4번)으로부터 값 하나 참조
print(arr_1d[-1]) # 음수로도 가능(-1번으로부터 값 하나 참조)

1
3
5
5


In [4]:
# 2d-array객체 생성
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 7],
                   [6, 8, 9],
                   [11, 17, 19]]) # 4행 3열

In [5]:
# Case1
# 처음(0번) 행/열 인덱스로부터 값 하나 참조
print(arr_2d[0,0])

# Case1(음수로 할 경우)
# –4번 행 인덱스와 –3번 열 인덱스로부터 값 하나 참조
print(arr_2d[-4,-3])

# Case2
# 2번 행 인덱스와 1번 열 인덱스로부터 값 하나 참조
print(arr_2d[2,1])

# Case2(음수로 할 경우)
# -2번 행/열 인덱스로부터 값 하나 참조
print(arr_2d[-2,-2])

1
1
8
8


In [6]:
# 음수 인덱싱의 활용 예

# Case1
# 3번 행 인덱스와 2번 열 인덱스로부터 값 하나를 참조하는 것보다
# 마지막 행열에 위치하므로 -1번 행열 인덱스로부터 참조하는 것이 빠르다.
print(arr_2d[-1,-1])

# Case2
# 가장 처음 행(0번)과 가장 마지막 열(-1번) 인덱스로부터 값 하나 참조
print(arr_2d[0,-1])

# Case3
# 가장 마지막 행(-1번)과 가장 처음 열(0번) 인덱스로부터 값 하나 참조
print(arr_2d[-1,0])

19
3
11


### 슬라이싱

In [7]:
# 슬라이싱
# 1d-array객체 생성
arr_1d = np.array([1, 2, 3, 4, 5])

In [8]:
# Case1
# 처음(0번)부터 2번 인덱스 번호 사이의 구간 추출
print(arr_1d[0:2])
print(arr_1d[:2]) # k1 = 0으로 생략 가능

[1 2]
[1 2]


In [9]:
# Case2
# 1번부터 4번 사이의 인덱스 번호 사이의 구간 추출
print(arr_1d[1:4])

# –4번부터 -1번 사이의 인덱스 번호 사이의 구간 추출
print(arr_1d[-4:-1])

# 1번부터 -1번 사이의 인덱스 번호 사이의 구간 추출
print(arr_1d[1:-1])

[2 3 4]
[2 3 4]
[2 3 4]


In [10]:
# Case3
# 3번부터 마지막(5번) 사이의 인덱스 번호 사이의 구간 추출
print(arr_1d[3:5])

# 3번부터 마지막 사이의 인덱스 번호 사이의 구간 추출
print(arr_1d[3:]) # k2=길이정보로 생략 가능
 
# -2번부터 마지막 사이의 인덱스 번호 사이의 구간 추출
print(arr_1d[-2:])

[4 5]
[4 5]
[4 5]


In [11]:
# 2d-array객체 생성
arr_2d = np.array([[1, 2, 3, 5],
                   [1, 3, 5, 7],
                   [2, 4, 6, 9],
                   [7, 11, 13, 17]]) # 4행 4열

In [12]:
# Case1
# 행 : 전체
# 열 : 처음(0번)부터 1번 열 인덱스 사이의 구간
print(arr_2d[0:4, 0])
print(arr_2d[:4, 0]) # r1=0으로 생략 가능
print(arr_2d[:, 0]) # r1=0이고 r2=행길이므로 생략 가능

[1 1 2 7]
[1 1 2 7]
[1 1 2 7]


In [13]:
# Case2
# 행/열 : 처음(인덱스 0번)부터 인덱스 3번(-1번) 사이의 구간
print(arr_2d[0:3, 0:3])
print(arr_2d[:3, :3]) # r1=c1=0으로 생략 가능
print(arr_2d[:-1, :-1]) # r1=c1=0으로 생략 가능

[[1 2 3]
 [1 3 5]
 [2 4 6]]
[[1 2 3]
 [1 3 5]
 [2 4 6]]
[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [14]:
# Case3
# 행/열 : 처음 바로 뒤(1번 또는 -3번)부터 마지막 바로 앞(-1번 또는 3번) 사이의 구간
print(arr_2d[1:3, 1:3])
print(arr_2d[-3:-1, -3:-1])
print(arr_2d[1:-1, 1:-1])

[[3 5]
 [4 6]]
[[3 5]
 [4 6]]
[[3 5]
 [4 6]]


In [15]:
# Case4
# 행 : 처음 바로 뒤(1번 또는 -3번)부터 마지막 바로 앞(-1번 또는 3번) 사이의 구간
# 열 : 전체
print(arr_2d[1:3, 0:4])
print(arr_2d[1:3, :]) # c1=0이고 c2=열길이이므로 생략 가능
print(arr_2d[1:-1, :]) # c1=0이고 c2=열길이이므로 생략 가능

[[1 3 5 7]
 [2 4 6 9]]
[[1 3 5 7]
 [2 4 6 9]]
[[1 3 5 7]
 [2 4 6 9]]


In [16]:
# Case5
# 행 : 마지막 행
# 열 : 열 전체
print(arr_2d[3, 0:4])
print(arr_2d[3, :]) # c1=0이고 c2=열길이이므로 생략 가능
print(arr_2d[-1, :]) # c1=0이고 c2=열길이이므로 생략 가능

[ 7 11 13 17]
[ 7 11 13 17]
[ 7 11 13 17]


In [17]:
# Case6
# 행/열 : 2번(또는 -2번)부터 마지막 인덱스 사이의 구간
print(arr_2d[2:4, 2:4])
print(arr_2d[2:, 2:]) # c2=열길이이므로 생략 가능
print(arr_2d[-2:, -2:]) # c2=열길이이므로 생략 가능

[[ 6  9]
 [13 17]]
[[ 6  9]
 [13 17]]
[[ 6  9]
 [13 17]]


## 1. N 차원 배열의 원소별 연산

### 단일 배열객체의 범용 함수

In [18]:
# 단일 배열객체에 대한 범용 함수
# 1d-array객체 생성
arr = np.array([0, 1, -4, 9, -16, 25])
print(arr)

[  0   1  -4   9 -16  25]


In [19]:
# abs : 원소별 절대값을 반환(abs는 파이썬 기본 내장함수로도 가능함)
arr_abs = np.abs(arr)
print(arr_abs)

# fabs : 원소별 절대값을 반환(abs보다 빠름)
arr_fabs = np.fabs(arr)
print(arr_fabs)

[ 0  1  4  9 16 25]
[ 0.  1.  4.  9. 16. 25.]


In [20]:
# sqrt : 원소별 제곱근 값 반환
# 음수는 nan 반환됨
arr_sqrt = np.sqrt(arr)
print(arr_sqrt)

[ 0.  1. nan  3. nan  5.]


/var/folders/bk/xfd679sj72v2213jc_8tf6gw0000gn/T/ipykernel_2117/2879652879.py:3: RuntimeWarning: invalid value encountered in sqrt
  arr_sqrt = np.sqrt(arr)


In [21]:
# square : 원소별 제곱 값을 반환
arr_square = np.square(arr)
print(arr_square)

[  0   1  16  81 256 625]


In [22]:
# exp : 원소별 밑이 e인 지수 함수 값을 반환
arr_exp = np.exp(arr)
print(arr_exp)

[1.00000000e+00 2.71828183e+00 1.83156389e-02 8.10308393e+03
 1.12535175e-07 7.20048993e+10]


In [23]:
# log : 원소별 자연로그 값을 반환
# 음수는 nan, 0은 -inf 반환됨
arr_log = np.log(arr)
print(arr_log)

# log10 : 원소별 상용로그 값을 반환
# 음수는 nan, 0은 -inf 반환됨
arr_log10 = np.log10(arr)
print(arr_log10)

[      -inf 0.                nan 2.19722458        nan 3.21887582]
[      -inf 0.                nan 0.95424251        nan 1.39794001]


/var/folders/bk/xfd679sj72v2213jc_8tf6gw0000gn/T/ipykernel_2117/629030723.py:3: RuntimeWarning: divide by zero encountered in log
  arr_log = np.log(arr)
/var/folders/bk/xfd679sj72v2213jc_8tf6gw0000gn/T/ipykernel_2117/629030723.py:3: RuntimeWarning: invalid value encountered in log
  arr_log = np.log(arr)
/var/folders/bk/xfd679sj72v2213jc_8tf6gw0000gn/T/ipykernel_2117/629030723.py:8: RuntimeWarning: divide by zero encountered in log10
  arr_log10 = np.log10(arr)
/var/folders/bk/xfd679sj72v2213jc_8tf6gw0000gn/T/ipykernel_2117/629030723.py:8: RuntimeWarning: invalid value encountered in log10
  arr_log10 = np.log10(arr)


In [24]:
# sign : 원소별 부호 값을 반환
# 양수면 1, 음수면 -1, 0은 0을 반환
arr_sign = np.sign(arr)
print(arr_sign)

[ 0  1 -1  1 -1  1]


In [25]:
# 단일 배열객체의 소숫점을 처리하는 범용 함수
# 1d-array객체 생성
arr = np.array([1.15, -2.33, 3.457, -4.095])
print(arr)

[ 1.15  -2.33   3.457 -4.095]


In [26]:
# round : 원소별 소수점을 원하는 자릿수까지 반올림한 값을 반환
arr_round = np.round(arr) # default는 0
print(arr_round)

arr_round_decimals_1 = np.round(arr, 1) #decimals 인자 값만 입력해도 됨
print(arr_round_decimals_1)

[ 1. -2.  3. -4.]
[ 1.2 -2.3  3.5 -4.1]


In [27]:
# ceil : 원소별 소수점을 올림한 값을 반환
arr_ceil = np.ceil(arr)
print(arr_ceil)

[ 2. -2.  4. -4.]


In [28]:
# floor : 원소별 소수점을 내림한 값을 반환
arr_floor = np.floor(arr)
print(arr_floor)

[ 1. -3.  3. -5.]


In [29]:
# trunc : 원소별 소수점을 잘라버린 값을 반환
arr_trunc = np.trunc(arr)
print(arr_trunc)

[ 1. -2.  3. -4.]


### 서로 다른 배열객체의 범용 함수

In [30]:
# 서로 배열객체에 대한 범용 함수
# 1d-array객체 생성
arr_1 = np.arange(5) # 0 1 2 3 4
print(arr_1)

arr_2 = np.arange(1, 10, step = 2) # 1 3 5 7 9
print(arr_2)

[0 1 2 3 4]
[1 3 5 7 9]


In [31]:
# add : 두 배열객체의 원소 별 덧셈
arr_add_1 = np.add(arr_1, arr_2)
print(arr_add_1)

# 연산자 +로 대신 가능
arr_add_2 = arr_1 + arr_2
print(arr_add_2)

[ 1  4  7 10 13]
[ 1  4  7 10 13]


In [32]:
# subtract : 두 배열객체의 원소 별 뺄셈
arr_subtract_1 = np.subtract(arr_1, arr_2)
print(arr_subtract_1)

# 연산자 -로 대신 가능
arr_subtract_2 = arr_1 - arr_2
print(arr_subtract_2)

[-1 -2 -3 -4 -5]
[-1 -2 -3 -4 -5]


In [33]:
# multiply : 두 배열객체의 원소 별 곱셈
arr_multiply_1 = np.multiply(arr_1, arr_2)
print(arr_multiply_1)

# 연산자 *로 대신 가능
arr_multiply_2 = arr_1 * arr_2
print(arr_multiply_2)

[ 0  3 10 21 36]
[ 0  3 10 21 36]


In [34]:
# divide : 두 배열객체의 원소 별 나눗셈
arr_divide_1 = np.divide(arr_1, arr_2)
print(arr_divide_1)

# 연산자 /로 대신 가능
arr_divide_2 = arr_1 / arr_2
print(arr_divide_2)

[0.         0.33333333 0.4        0.42857143 0.44444444]
[0.         0.33333333 0.4        0.42857143 0.44444444]


In [35]:
# mod : 두 배열객체의 원소 별 나눈 후 나머지
arr_mod_1 = np.mod(arr_1, arr_2)
print(arr_mod_1)

# 연산자 %로 대신 가능
arr_mod_2 = arr_1 % arr_2
print(arr_mod_2)

[0 1 2 3 4]
[0 1 2 3 4]


In [36]:
# 두 배열객체가 서로 다른 길이, 차원, shape를 가질 경우
# Case1. 길이가 다른 경우
# 길이가 3인 1d-array 생성
arr_1d_3 = np.array([1, 2, 3])
print(arr_1d_3) # 확인
print(arr_1d_3.shape) # shape 확인

# 길이가 1인 1d-array 생성
arr_1d_1 = np.array([5])
print(arr_1d_1) # 확인
print(arr_1d_1.shape) # shape 확인

# 두 배열객체의 합은 길이가 3인 1d-array가 됨
arr_add = arr_1d_3 + arr_1d_1
print(arr_add) # 확인
print(arr_add.shape) # shape 확인

[1 2 3]
(3,)
[5]
(1,)
[6 7 8]
(3,)


In [37]:
# Case2. 차원이 다른 경우
# 행길이 3, 열길이 3인 2d-array 생성
arr_2d_3x3 = np.array([[1, 4, 7],
                       [2, 5, 8],
                       [3, 6, 9]])

print(arr_2d_3x3) # 확인
print(arr_2d_3x3.shape) # shape 확인

# 길이가 3인 1d-array 생성
arr_1d_3 = np.array([1, 0, -1])
print(arr_1d_3) # 확인
print(arr_1d_3.shape) # shape 확인

# 두 배열객체의 합은 행길이 3, 열길이 3인 2d-array가 됨
arr_add = arr_2d_3x3 + arr_1d_3
print(arr_add) # 확인
print(arr_add.shape) # shape 확인

[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)
[ 1  0 -1]
(3,)
[[2 4 6]
 [3 5 7]
 [4 6 8]]
(3, 3)


In [38]:
# Case3. shape가 다른 경우
# 행길이 1, 열길이 3인 2d-array 생성
arr_2d_1x3 = np.array([[1, 2, 3]])

print(arr_2d_1x3) # 확인
print(arr_2d_1x3.shape) # shape 확인
print(arr_2d_1x3.ndim) # 차원 확인

# 행길이 3, 열길이 1인 2d-array 생성
arr_2d_3x1 = np.array([[1],
                       [0],
                       [-1]]) 

print(arr_2d_3x1) # 확인
print(arr_2d_3x1.shape) # shape 확인
print(arr_2d_3x1.ndim) # 차원 확인

# 두 배열객체의 합은 행길이 3, 열길이 3인 2d-array가 됨
arr_add = arr_2d_1x3 + arr_2d_3x1
print(arr_add) # 확인
print(arr_add.shape) # shape 확인

[[1 2 3]]
(1, 3)
2
[[ 1]
 [ 0]
 [-1]]
(3, 1)
2
[[2 3 4]
 [1 2 3]
 [0 1 2]]
(3, 3)
