# Numpy의 주요 함수와 메소드

In [1]:
# Numpy 패키지 불러오기
import numpy as np # 넘파이 패키지를 np라는 별칭으로 호출

#### [ 형상 변환 메소드 ]

- Numpy에서 ndarray 객체들은 아래와 같은 메소드들을 통해 형상 변환이 가능하다.

|메소드|기능|
|:------|:---------|
|배열객체.reshape()|배열 객체를 입력된 shape로 변환 <br>-1은 원래 배열 객체의 길이와 길이와 남은 차원으로 알아서 정해지는 것을 의미함|
|배열객체.ravel() <br> 배열객체.ravel()| 다차원 배열객체를 1차원으로 평탄화 함 |
|배열객체.transpose()| 배열의 축을 교환함 |

## 형상 변환 메소드

In [2]:
# .reshape()
# 배열 객체를 입력된 shape로 변환

# 길이가 8인 1d-array객체 생성
arr_1d = np.arange(8)
print(arr_1d)

# 행 길이가 2이고 열 길이가 4인 2d-array객체로 변환
arr_2d_2x4 = arr_1d.reshape(2,4)
print(arr_2d_2x4)

# 행 길이가 4이고 열 길이가 2인 2d-array객체로 변환
arr_2d_4x2 = arr_1d.reshape(4,2)
print(arr_2d_4x2)

# 행 길이가 3이고 열 길이가 3인 2d-array객체로 변환
# .reshape() 메소드는 총 원소의 수(size)가 같지 않을 경우 변환이 되지 않는다.
arr_2d_3x3 = arr_1d.reshape(3,3)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


ValueError: cannot reshape array of size 8 into shape (3,3)

In [3]:
# reshape 메소드 활용 예 1 : (3,3)인 2차원 배열 변환
# 길이가 9인 1d-array객체 생성
arr_1d = np.arange(9)
print(arr_1d)

# 행 길이가 3이고 열 길이가 3인 2d-array객체로 변환
arr_2d_3x3 = arr_1d.reshape(3,3)
print(arr_2d_3x3)

# -1 이용해 2d-array객체로 변환
# 행의 수를 3으로 지정하고 남은 차원(열)은 알아서 정함
arr_2d_3xN = arr_1d.reshape(3,-1)
print(arr_2d_3xN)

# 열의 수를 3으로 지정하고 남은 차원(행)은 알아서 정함
arr_2d_Nx3 = arr_1d.reshape(-1,3)
print(arr_2d_Nx3)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# reshape 메소드 활용 예 2 : (3,3)인 2차원 배열 생성
# 원소가 0~8이면서 (3,3)인 2d-array객체 생성
# 방법1
arr1 = np.array([[0, 1, 2],
                 [3, 4, 5],
                 [6, 7, 8]])
print(arr1)

# 방법2
arr2 = np.arange(9).reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
# reshape 메소드 활용 예 3 : (3,2,2)인 3차원 배열 생성
# 원소가 0~11이면서 층이 3이고 행/열 길이가 2인 3d-array객체 생성
# 방법1
arr4 = np.arange(12).reshape(3,2,2)
print(arr4)

# 방법2
arr5 = np.arange(12).reshape(3,2,-1) # 층 수 3, 행 수 2로 지정, 남은 차원(열) 자동
print(arr5)

# 방법3
arr6 = np.arange(12).reshape(-1,2,2) # 행/열의 수는 2로 지정, 남은 차원(층) 자동
print(arr6)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [6]:
# 다차원 배열 객체를 1차원 배열로 변환(평탄화)

# reshape 메소드를 활용
# (3,3)인 2차원 배열을 길이가 9인 1차원 배열로 변환
arr1_1d = arr1.reshape(9)
print(arr1_1d)

# (3,2,2)인 3차원 배열을 길이가 12인 1차원 배열로 변환
arr4_1d = arr4.reshape(12)
print(arr4_1d)

[0 1 2 3 4 5 6 7 8]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
# .ravel()
# 다차원 배열 객체를 1차원으로 평탄화함

arr2_1d = arr2.ravel() # 길이를 입력하지 않아도 됨
print(arr2_1d)

arr5_1d = arr5.ravel() # 길이를 입력하지 않아도 됨
print(arr5_1d)

[0 1 2 3 4 5 6 7 8]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
# .flatten()
# 다차원 배열 객체를 1차원으로 평탄화함
arr4_1d = arr4.flatten() # 길이를 입력하지 않아도 됨
print(arr4_1d)

arr6_1d = arr6.flatten() # 길이를 입력하지 않아도 됨
print(arr6_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
# .transpose()
# 배열의 축을 교환함
arr_2d = np.arange(8).reshape(4,2)
print(arr_2d)

arr_2d_T = arr_2d.transpose() # 축 교환
print(arr_2d_T)

# .T 로도 바로 가능
print(arr_2d.T)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 2 4 6]
 [1 3 5 7]]
[[0 2 4 6]
 [1 3 5 7]]
